### ISSUE TITLE
twikoo为false但依旧发起了请求

### ISSUE THREAD

**Issue by D-Sketon** [zkz098/hexo-theme-shokaX#10]
### 建议描述

![image](https://user-images.githubusercontent.com/49871906/214292424-f0b4bc71-29d0-48c2-847d-39c554051bd3.png)
（好臭的url

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
终于有人发现力(喜)
话说这个是不是应该使用问题反馈模板

**Comment by zkz098** [comment]
0.0.4已修复
