### ISSUE TITLE
请求在页脚加入不蒜子和建站时间

### ISSUE THREAD

**Issue by D-Sketon** [zkz098/hexo-theme-shokaX#11]
### 建议描述

像这样的
![image](https://user-images.githubusercontent.com/49871906/214293814-84d21aa9-231e-45cd-9142-b704677a5ee6.png)

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
可以参考 [插件系统文档](https://www.kaitaku.xyz/webbuild/shokaXplugin/) 使用新加的status注入点先行实现
编写后的使用可以参考[awesome-shokaX](https://github.com/zkz098/awesome-shokaX)

**Comment by zkz098** [comment]
已通过`hexo-shokax-busuanzi`和`hexo-shokax-create-time`解决
