### ISSUE TITLE
footer.since显示异常

### ISSUE THREAD

**Issue by D-Sketon** [zkz098/hexo-theme-shokaX#12]
### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

![image](https://user-images.githubusercontent.com/49871906/214301642-bf0634b0-03b7-4391-849f-9174c9af0f70.png)
正确显示应该是© 2021-2023吧（）

### 复现步骤

_config.yml无需改变

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
0.0.4已修复
