### ISSUE TITLE
fancybox和katex不可用

### ISSUE THREAD

**Issue by D-Sketon** [zkz098/hexo-theme-shokaX#13]
### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

![image](https://user-images.githubusercontent.com/49871906/214309475-9113f397-8455-462e-acdc-5e7a7bdddbe6.png)
js和css404，造成了图片排列在页脚底下的逆天情况
![image](https://user-images.githubusercontent.com/49871906/214309806-425bb558-a0d8-427f-a5ff-537182ad20e9.png)
感觉bug有点多，到时候我就直接交PR算了（）

### 复现步骤

打开fancybox，并随便在md里插入一张图片

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
BUG问题是因为shokaX至今没有过完整的功能测试,所以很多功能都是理论上的能run
目前已经在修了,这个fancybox的问题应该是依赖加载的时候npm优先级过高导致的

**Comment by D-Sketon** [comment]
辛苦了

**Comment by zkz098** [comment]
0.0.4修复了fancybox的问题，但是katex目前没法确认

**Comment by D-Sketon** [comment]
> 0.0.4修复了fancybox的问题，但是katex目前没法确认

katex依然有问题
![image](https://user-images.githubusercontent.com/49871906/214325869-0ba9f3e4-1192-42bf-9219-63477df444d8.png)

**Comment by zkz098** [comment]
突然知道哪有问题了
本地已经修了,等明天凑个0.0.5再提交

**Comment by zkz098** [comment]
0.0.5理论上修复了katex的问题
