### ISSUE TITLE
卡片显示异常？

### ISSUE THREAD

**Issue by D-Sketon** [zkz098/hexo-theme-shokaX#14]
### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

好像缺了圆角，阴影？
ShokaX:
![image](https://user-images.githubusercontent.com/49871906/214327164-a1f1ba62-7f64-41db-a4d9-d1e990ba3e34.png)
Shoka:
![image](https://user-images.githubusercontent.com/49871906/214327225-a15a1871-4a86-454b-bf81-2fd85d439859.png)

### 复现步骤

/

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
目前已经确认是card的info生成异常了,但是原因还在排查中
阴影和圆角问题出现的比较奇怪,因为shokaX没有改动那一块的CSS

**Comment by zkz098** [comment]
阴影和圆角也是info生成异常引起的,但info异常原因还在排查
