### ISSUE TITLE
标题多了一条竖线

### ISSUE THREAD

**Issue by D-Sketon** [zkz098/hexo-theme-shokaX#15]
### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

![image](https://user-images.githubusercontent.com/49871906/214328253-220e8d67-7fd7-4610-9fe4-ae71e02cde68.png)
![image](https://user-images.githubusercontent.com/49871906/214328335-bcc703d6-5a19-42c3-beda-7e49026ca8d3.png)
等等页面标题右边多了一条竖线？

### 复现步骤

/

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
已修,把njk过滤器看成文本了
