### ISSUE TITLE
header文章超链接错误

### ISSUE THREAD

**Issue by D-Sketon** [zkz098/hexo-theme-shokaX#16]
### 问题发生位置

Hexo渲染不正确(文字undefine或空白等)

### 问题描述

![image](https://user-images.githubusercontent.com/49871906/214329381-e9713cc7-846c-4d0f-a674-4550d99138b7.png)
该选项跳转到的是：
![image](https://user-images.githubusercontent.com/49871906/214329421-7dc68ffb-8f72-43cc-8c6b-72df41f545db.png)
好像成了`javascript:void(0)`？= =

### 复现步骤

/

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
本地已修,dropdown判定条件有问题
