### ISSUE TITLE
0.0.4后文章目录异常，文章滚动异常

### ISSUE THREAD

**Issue by D-Sketon** [zkz098/hexo-theme-shokaX#18]
### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

sidebar文章目录得点好几次才**有可能**跳转到正确的anchor
还有下滑/上滑的时候到了anchor有时会莫名弹出header，还会发生抖动？
![bug](https://fastly.jsdelivr.net/gh/D-Sketon/blog-img/shokaX-bug1.gif)
也许与 de773de1029c4b458b5dd27a9ec94166d3457de9 有关？

### 复现步骤

/

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
看起来确实和[de773de](https://github.com/zkz098/hexo-theme-shokaX/commit/de773de1029c4b458b5dd27a9ec94166d3457de9)有关,我把这个提交撤销一下

**Comment by zkz098** [comment]
0.0.7已修复
