### ISSUE TITLE
categories页面缺东西

### ISSUE THREAD

**Issue by D-Sketon** [zkz098/hexo-theme-shokaX#19]
### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

好像缺了点什么= =
ShokaX:
![image](https://user-images.githubusercontent.com/49871906/214504572-8f6f8516-fa4a-4d2c-bbee-a59555aaf717.png)
Shoka:
![image](https://user-images.githubusercontent.com/49871906/214504586-a2d262a0-7bf2-4810-821e-38e551ef9a9c.png)

### 复现步骤

/

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
已知问题,正在修复

**Comment by zkz098** [comment]
0.0.8已修
