### ISSUE TITLE
firework关闭后报错

### ISSUE THREAD

**Issue by D-Sketon** [zkz098/hexo-theme-shokaX#45]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

![image](https://user-images.githubusercontent.com/49871906/222061810-20a45952-e23a-4d01-89c3-15db4acdeeda.png)

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
shokaX早期合并js的时候把fireworks和sidebar合并了，等下个版本拆一下就行了

**Comment by zkz098** [comment]
0.2.0-rc5理论上修复
