### ISSUE TITLE
对新用户不友好

### ISSUE THREAD

**Issue by Ezgx** [zkz098/hexo-theme-shokaX#46]
### 建议描述

作者大大蒙都简化一下，跟一般的主题一样，这样太难了，对小白实在不友好

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
ShokaX的SXC已经极大简化安装过程了，原版shoka比这个复杂的多 (
具体是哪个方面需要优化，详细说一下

**Comment by zkz098** [comment]
请详细说明具体需要优化的方面，这种描述难以看出问题所在

**Comment by zkz098** [comment]
因为长时间无回复且issue信息过少、意义不明确，此issue已关闭。
如果有后续回复可以开一个新issus并引用此issue。
