### ISSUE TITLE
烟花动画在长时间加载时卡住不会消失

### ISSUE THREAD

**Issue by D-Sketon** [zkz098/hexo-theme-shokaX#49]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

也许不算BUG？但比较影响实际的显示效果
![image](https://user-images.githubusercontent.com/49871906/224762598-0abc2639-3449-48ad-9d5f-0da4cc5e0c6d.png)

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
在我这边只有加载完成的一瞬间会卡一下，无法复现这种不消失的情况
也许是时间不够长 ()

**Comment by D-Sketon** [comment]
> 在我这边只有加载完成的一瞬间会卡一下，无法复现这种不消失的情况 也许是时间不够长 ()

其实也不是不消失，就是当网络卡顿或者文章有大量DOM的时候动画卡顿的时间特别长，影响观感（）
可以尝试添加一篇500k+的文章复现（）

**Comment by zkz098** [comment]
> 其实也不是不消失，就是当网络卡顿或者文章有大量DOM的时候动画卡顿的时间特别长，影响观感（） 可以尝试添加一篇500k+的文章复现（）

大概率还是pjax的锅，调试不出来具体问题 ()
这个暂时没法修，等找到pjax替代方案就能解决了（目前尚未找到合适的替代方案）

**Comment by D-Sketon** [comment]
> > 其实也不是不消失，就是当网络卡顿或者文章有大量DOM的时候动画卡顿的时间特别长，影响观感（） 可以尝试添加一篇500k+的文章复现（）
> 
> 大概率还是pjax的锅，调试不出来具体问题 ()
> 这个暂时没法修，等找到pjax替代方案就能解决了（目前尚未找到合适的替代方案）
> 

目前看来应该是pjax加载dom的时候阻塞了页面？

**Comment by zkz098** [comment]
> 目前看来应该是pjax加载dom的时候阻塞了页面？感觉无解了

应该是这样，因为Shoka使用的Pjax会对DOM做遍历操作，这导致如果DOM数量大或者网络抽风的话就会被Pjax整个阻塞住。(anime.js的后续操作因为性能瓶颈被卡住了，所以产生了烟花动画被拉长的效果)
目前确实无解，因为没有替代方案

**Comment by D-Sketon** [comment]
> 应该是这样，因为Shoka使用的Pjax会对DOM做遍历操作，这导致如果DOM数量大或者网络抽风的话就会被Pjax整个阻塞住。(anime.js的后续操作因为性能瓶颈被卡住了，所以产生了烟花动画被拉长的效果) 目前确实无解，因为没有替代方案

也许可以取消点击a标签时的动画，从根源上解决问题（）

**Comment by zkz098** [comment]
> 也许可以取消点击a标签时的动画，从根源上解决问题（）

好方法 ()

**Comment by zkz098** [comment]
> > 也许可以取消点击a标签时的动画，从根源上解决问题（）
> 
> 好方法 ()

目前已经改完了()，等明天发个0.2.1版本
