### ISSUE TITLE
英语语言吸顶溢出

### ISSUE THREAD

**Issue by D-Sketon** [zkz098/hexo-theme-shokaX#50]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

![image](https://user-images.githubusercontent.com/49871906/225559954-88a9d500-03b2-4fce-bb82-924da16f73f3.png)
如图

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
以及sidebar溢出
![image](https://user-images.githubusercontent.com/49871906/225560854-7b33047b-53e1-4f04-a1f9-1c7456353c10.png)

**Comment by zkz098** [comment]
这个应该只能叫“特性”()
如果把导航栏设置成自动调整高度会非常难看，计划加入导航栏切换宽度设置

**Comment by zkz098** [comment]
已加入实验性设置，理论上可以解决
