### ISSUE TITLE
第二页但sidebar并没有后退按钮

### ISSUE THREAD

**Issue by D-Sketon** [zkz098/hexo-theme-shokaX#51]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

![image](https://user-images.githubusercontent.com/49871906/226240692-58e1b51b-dbed-4533-b902-a884fcbc5a98.png)

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
![image](https://user-images.githubusercontent.com/92242020/227225165-188f3d58-cc96-439c-980a-a3b6c858eca9.png)
有点玄幻()
page变量中的prev_link是空的，所以没有后退按钮
目前打了个补丁，等[#50]修好了凑一个0.2.1发布 ()
