### ISSUE TITLE
SXC指令无法使用

### ISSUE THREAD

**Issue by xiutz** [zkz098/hexo-theme-shokaX#53]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

其他问题

### 问题描述

使用$ SXC install shokaX时，无法正常运行

### 复现步骤

使用以下指令
$ SXC install shokaX
bash: SXC: command not found
![image](https://user-images.githubusercontent.com/82282782/229314093-0b73d829-910f-4835-a686-d2b3bb1257f0.png)

### 相关配置

$ hexo version
INFO  Validating config
hexo: 6.3.0
hexo-cli: 4.3.0
os: win32 10.0.19044
node: 16.13.1
v8: 9.4.146.24-node.14
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 1.1.1l+quic
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV

$ npm version
{
  'hexo-site': '0.0.0',
  npm: '8.1.2',
  node: '16.13.1',
  v8: '9.4.146.24-node.14',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
nodejs的global文件夹是不是没加到path里
换成`npx SXC install shokaX`试试

**Comment by xiutz** [comment]
用npx SXC install shokaX可以运行了，但是，相应的主题文件并没有写入到themes下，好像被放到了
node_modules/hexo-theme-shokax下面了，这样是正常的？

**Comment by zkz098** [comment]
> 用npx SXC install shokaX可以运行了，但是，相应的主题文件并没有写入到themes下，好像被放到了 node_modules/hexo-theme-shokax下面了，这样是正常的？

正常的，用npm源安装的都是这个路径。

**Comment by xiutz** [comment]
好的，这个还是和一般的主题使用有点区别哈。希望后面文档能补充下这个描述，会对小白友好一点
