### ISSUE TITLE
代码块显示异常

### ISSUE THREAD

**Issue by QAdminzhangQ** [zkz098/hexo-theme-shokaX#7]
![image](https://user-images.githubusercontent.com/101789984/211032089-a76218c6-dd61-4280-9e41-34198c36b71e.png)
这里的按钮显示位置错误

**Comment by zkz098** [comment]
此BUG在测试环境中无法稳定复现,请检查`hexo highlight`是否关闭,渲染器是否升级为最新版

**Comment by zkz098** [comment]
已解决,原因为未关闭`hexo highlight`
