### ISSUE TITLE
天气组件无法正常显示

### ISSUE THREAD

**Issue by QAdminzhangQ** [zkz098/hexo-theme-shokaX#8]
### 问题描述

已经在主题配置文件中填入api key qweather已经设置为true 但天气组件仍然无法显示

### 复现步骤

重新生成静态文件 确认api key有效

### 注意事项

- [x] 我已确认以上事项

**Comment by zkz098** [comment]
可能是天气组件延迟加载问题,正在测试

**Comment by zkz098** [comment]
经过测试,此问题无法复现,请尝试升级shokaX版本
